from langchain_core.messages import HumanMessage, AIMessage, ToolMessage

{
    'messages': [
        HumanMessage(
            content='在新浪上帮我查一下携程股价', additional_kwargs={}, response_metadata={},
            id='38d3e0d6-80be-4e45-a999-28e2eeee8be7'),
        AIMessage(
            content='', additional_kwargs={},
            response_metadata={
                'finish_reason': 'tool_calls',
                'model_name': 'qwen-plus',
                'model_provider': 'openai'},
            id='lc_run--980b6705-e94c-450a-83e1-8221b942058f',
            tool_calls=[{'name': 'new_page',
                         'args': {
                             'url': 'https://www.sina.com.cn'},
                         'id': 'call_7971b474ad88474a99b7e8',
                         'type': 'tool_call'}]),
        ToolMessage(
            content='# new_page response\n## Pages\n0: about:blank\n1: https://www.sina.com.cn/ [selected]',
            name='new_page', id='3563aaf6-5c30-4eec-8d25-a20136d92522',
            tool_call_id='call_7971b474ad88474a99b7e8'),
        AIMessage(
            content='', additional_kwargs={},
            response_metadata={
                'finish_reason': 'tool_calls',
                'model_name': 'qwen-plus',
                'model_provider': 'openai'},
            id='lc_run--3ccf2c57-7b3b-437e-9448-cd5fbcd8afc9',
            tool_calls=[
                {'name': 'take_snapshot', 'args': {},
                 'id': 'call_1b5d83816ebe4aa081efda',
                 'type': 'tool_call'
                 }]),
        ToolMessage(content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
                    name='take_snapshot', id='5116fffb-1c05-4e78-990c-14f09c5fb028',
                    tool_call_id='call_1b5d83816ebe4aa081efda'), AIMessage(content='', additional_kwargs={},
                                                                           response_metadata={
                                                                               'finish_reason': 'tool_calls',
                                                                               'model_name': 'qwen-plus',
                                                                               'model_provider': 'openai'},
                                                                           id='lc_run--abc0ac9a-5d50-4928-8636-45e884a4d162',
                                                                           tool_calls=[{'name': 'fill',
                                                                                        'args': {'uid': '1_8',
                                                                                                 'value': '携程 股价'},
                                                                                        'id': 'call_8011519124fb4b17a254a2',
                                                                                        'type': 'tool_call'}]),
        ToolMessage(content='No snapshot found. Use take_snapshot to capture one.', name='fill',
                    id='d35ec00c-b314-49db-9913-fc5773802d1a', tool_call_id='call_8011519124fb4b17a254a2',
                    status='error'), AIMessage(content='', additional_kwargs={},
                                               response_metadata={'finish_reason': 'tool_calls',
                                                                  'model_name': 'qwen-plus',
                                                                  'model_provider': 'openai'},
                                               id='lc_run--580d7ecf-10a2-4565-8f09-c6a719c3818c', tool_calls=[
                {'name': 'take_snapshot', 'args': {}, 'id': 'call_eabf04473df24d5bbe5e98', 'type': 'tool_call'}]),
        ToolMessage(content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
                    name='take_snapshot', id='7ebaedc9-eee4-4469-9025-53a7b2d2aad0',
                    tool_call_id='call_eabf04473df24d5bbe5e98'), AIMessage(content='', additional_kwargs={},
                                                                           response_metadata={
                                                                               'finish_reason': 'tool_calls',
                                                                               'model_name': 'qwen-plus',
                                                                               'model_provider': 'openai'},
                                                                           id='lc_run--636f9ba8-9db3-4cc9-a110-acb4a021b28d',
                                                                           tool_calls=[{'name': 'click',
                                                                                        'args': {'uid': '1_9'},
                                                                                        'id': 'call_33265804e3564f848d8d87',
                                                                                        'type': 'tool_call'}]),
        ToolMessage(content='No snapshot found. Use take_snapshot to capture one.', name='click',
                    id='5c00aa31-85ca-457d-95b6-685b6290e9de', tool_call_id='call_33265804e3564f848d8d87',
                    status='error'), AIMessage(content='', additional_kwargs={},
                                               response_metadata={'finish_reason': 'tool_calls',
                                                                  'model_name': 'qwen-plus',
                                                                  'model_provider': 'openai'},
                                               id='lc_run--e2c89c35-a884-4555-ad98-0d56997e96b1', tool_calls=[
                {'name': 'take_snapshot', 'args': {}, 'id': 'call_a1943f5227b24b71b9ed9b', 'type': 'tool_call'}]),
        ToolMessage(content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
                    name='take_snapshot', id='6b4ce6bb-0b3d-44e5-a8dd-5755c7c44a2b',
                    tool_call_id='call_a1943f5227b24b71b9ed9b'), AIMessage(content='', additional_kwargs={},
                                                                           response_metadata={
                                                                               'finish_reason': 'tool_calls',
                                                                               'model_name': 'qwen-plus',
                                                                               'model_provider': 'openai'},
                                                                           id='lc_run--68a45dfe-fc88-4d42-9847-7bad7d72bb46',
                                                                           tool_calls=[{'name': 'navigate_page',
                                                                                        'args': {
                                                                                            'url': 'https://finance.sina.com.cn/stock'},
                                                                                        'id': 'call_2d1ff15c90a8418da2bf72',
                                                                                        'type': 'tool_call'}]),
        ToolMessage(
            content='# navigate_page response\n## Pages\n0: https://finance.sina.com.cn/stock/?wm=3049_000537121077 [selected]',
            name='navigate_page', id='be345762-0a16-4850-809b-a5c6502cf45d',
            tool_call_id='call_2d1ff15c90a8418da2bf72'), AIMessage(content='', additional_kwargs={},
                                                                   response_metadata={
                                                                       'finish_reason': 'tool_calls',
                                                                       'model_name': 'qwen-plus',
                                                                       'model_provider': 'openai'},
                                                                   id='lc_run--e587d1d7-929b-4885-9c46-5d14614427cb',
                                                                   tool_calls=[
                                                                       {'name': 'take_snapshot', 'args': {},
                                                                        'id': 'call_befe5cdb2c004da6b38f7c',
                                                                        'type': 'tool_call'}]),
        ToolMessage(
            content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
            name='take_snapshot', id='78769c4f-2778-4e12-aeab-0ebc914e82fd',
            tool_call_id='call_befe5cdb2c004da6b38f7c'),
        AIMessage(content='', additional_kwargs={},
                  response_metadata={
                      'finish_reason': 'tool_calls',
                      'model_name': 'qwen-plus',
                      'model_provider': 'openai'},
                  id='lc_run--4eb4301b-f8ac-4798-9673-a6b7c1c6dcbe',
                  tool_calls=[{'name': 'fill',
                               'args': {'uid': '1_10',
                                        'value': '携程 股价'},
                               'id': 'call_8990e50441f54d938e0a71',
                               'type': 'tool_call'}]),
        ToolMessage(content='No snapshot found. Use take_snapshot to capture one.', name='fill',
                    id='087ac2d4-a1b4-405a-9e00-7323a240f2d0', tool_call_id='call_8990e50441f54d938e0a71',
                    status='error'),
        AIMessage(content='', additional_kwargs={},
                  response_metadata={'finish_reason': 'tool_calls',
                                     'model_name': 'qwen-plus',
                                     'model_provider': 'openai'},
                  id='lc_run--fe6dec16-0479-4928-aad4-e22164bad8fa', tool_calls=[
                {'name': 'take_snapshot', 'args': {}, 'id': 'call_1c16d2353a3e42fca013fe', 'type': 'tool_call'}]),
        ToolMessage(content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
                    name='take_snapshot', id='51d288db-6988-49ee-8e97-7d6470a2dbe6',
                    tool_call_id='call_1c16d2353a3e42fca013fe'), AIMessage(content='', additional_kwargs={},
                                                                           response_metadata={
                                                                               'finish_reason': 'tool_calls',
                                                                               'model_name': 'qwen-plus',
                                                                               'model_provider': 'openai'},
                                                                           id='lc_run--27ef25e2-23f8-48c2-abfe-6dc02e3ae79c',
                                                                           tool_calls=[{'name': 'click',
                                                                                        'args': {'uid': '1_11'},
                                                                                        'id': 'call_89b0d8dae25f494aaa5cd6',
                                                                                        'type': 'tool_call'}]),
        ToolMessage(content='No snapshot found. Use take_snapshot to capture one.', name='click',
                    id='7906ebbd-2dc9-4709-ae2d-51cbfc9d069e', tool_call_id='call_89b0d8dae25f494aaa5cd6',
                    status='error'), AIMessage(content='', additional_kwargs={},
                                               response_metadata={'finish_reason': 'tool_calls',
                                                                  'model_name': 'qwen-plus',
                                                                  'model_provider': 'openai'},
                                               id='lc_run--3d202b18-6439-4653-9b2b-9b1941821238', tool_calls=[
                {'name': 'take_snapshot', 'args': {}, 'id': 'call_a6dcfc19c96641f4815400', 'type': 'tool_call'}]),
        ToolMessage(content='# take_snapshot response\n## Page content\nuid=1_0 RootWebArea\n',
                    name='take_snapshot', id='9f24c74f-abc9-4126-abc5-950593c150ca',
                    tool_call_id='call_a6dcfc19c96641f4815400'), AIMessage(content='', additional_kwargs={},
                                                                           response_metadata={
                                                                               'finish_reason': 'tool_calls',
                                                                               'model_name': 'qwen-plus',
                                                                               'model_provider': 'openai'},
                                                                           id='lc_run--4b687ea0-829d-4e89-a87d-ba1f872e988d',
                                                                           tool_calls=[{'name': 'navigate_page',
                                                                                        'args': {
                                                                                            'url': 'https://quote.finance.sina.com.cn'},
                                                                                        'id': 'call_bc1906cc386c4a5b858c5a',
                                                                                        'type': 'tool_call'}])]}
