#!/usr/bin/env python
"""
FivcPlayground CLI

Command-line interface for runtime FivcPlayground agents and tools.
"""

import asyncio
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

import typer
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

from fivcplayground.agents import create_agent_async
from fivcplayground.agents.types.repositories import FileAgentConfigRepository
from fivcplayground.backends.chroma import (
    ChromaEmbeddingBackend,
)
from fivcplayground.backends.strands import (
    StrandsAgentBackend,
    StrandsModelBackend,
    StrandsToolBackend,
)
from fivcplayground.embeddings.types.repositories import FileEmbeddingConfigRepository
from fivcplayground.models.types.repositories import FileModelConfigRepository
from fivcplayground.tools import create_builtin_tools_async, create_tool_retriever_async
from fivcplayground.tools.types.repositories import FileToolConfigRepository
from fivcplayground.utils import OutputDir

load_dotenv()

app = typer.Typer(
    name="FivcPlayground",
    help="FivcPlayground - " "Personal Simple Generic Agents",
    rich_markup_mode="rich",
)

console = Console()


@app.command()
def run(
    agent_name: str = typer.Argument("default", help="Type of agent to run"),
    query: Optional[str] = typer.Option(
        None,
        "--query",
        "-q",
        help="User query to process (if not provided, will prompt interactively)",
    ),
    output: Optional[Path] = typer.Option(
        None, "--output", "-o", help="Output file path"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be done without executing"
    ),
    verbose: bool = typer.Option(
        False, "--verbose", "-v", help="Enable verbose output"
    ),
):
    """
    Run a FivcPlayground agent
    """
    asyncio.run(_run_async(agent_name, query, output, dry_run, verbose))


async def _run_async(
    agent_name: str,
    query: Optional[str],
    output: Optional[Path],
    dry_run: bool,
    verbose: bool,
):
    """Async implementation of the run command"""
    model_backend = StrandsModelBackend()
    model_config_repository = FileModelConfigRepository()

    tool_backend = StrandsToolBackend()
    tool_config_repository = FileToolConfigRepository()

    embedding_backend = ChromaEmbeddingBackend()
    embedding_config_repository = FileEmbeddingConfigRepository()

    agent_backend = StrandsAgentBackend()
    agent_config_repository = FileAgentConfigRepository()

    tools = await create_builtin_tools_async(tool_backend=tool_backend)
    tool_retriever = await create_tool_retriever_async(
        tools=tools,
        tool_backend=tool_backend,
        tool_config_repository=tool_config_repository,
        embedding_backend=embedding_backend,
        embedding_config_repository=embedding_config_repository,
        embedding_config_id="default",
    )

    console.print(
        Panel.fit(
            Text("FivcPlayground Agent Runner", style="bold blue"),
            subtitle="Intelligent Agent Ecosystem",
        )
    )

    if query is None:
        query = typer.prompt("Enter your query")
        if not query:
            console.print("[red]❌ Query cannot be empty[/red]")
            raise typer.Exit(1)

    agent_runnable = await create_agent_async(
        model_backend=model_backend,
        model_config_repository=model_config_repository,
        agent_backend=agent_backend,
        agent_config_repository=agent_config_repository,
        agent_config_id=agent_name,
        raise_exception=False,
    )
    if not agent_runnable:
        console.print(f"[red]❌ Unknown agent type: {agent_name}[/red]")
        agent_ids = [i.id for i in agent_config_repository.list_agent_configs()]
        console.print(f"Available agents: {agent_ids}")
        raise typer.Exit(1)

    if dry_run:
        console.print(f"[yellow]DRY RUN:[/yellow] Would run {agent_name} agent")
        if query:
            console.print(f"[yellow]Query:[/yellow] {query}")
        if output:
            console.print(f"[yellow]Output:[/yellow] {output}")
        return

    try:
        agent_result = await agent_runnable.run_async(
            query=query,
            tool_retriever=tool_retriever,
        )
        print(agent_result.model_dump_json())
        console.print("[green]✅ Agent completed successfully![/green]")
    except Exception as e:
        console.print(f"[red]❌ Error runtime agent: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def clean():
    """
    Clean up temporary files generated by FivcPlayground
    """
    console.print("[yellow]Cleaning up temporary files...[/yellow]")

    try:
        # Clean temp directories
        output_dir = OutputDir()
        output_dir.cleanup(ignore_errors=False)
        console.print("[green]✅ Cleanup completed[/green]")

    except Exception as e:
        console.print(f"[red]❌ Error during cleanup: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def web(
    port: int = typer.Option(
        8501, "--port", "-p", help="Port to run the web interface on"
    ),
    host: str = typer.Option(
        "0.0.0.0", "--host", "-h", help="Host to bind the web interface to"
    ),
    debug: bool = typer.Option(False, "--debug", help="Run in debug mode"),
):
    """
    Launch the FivcPlayground web interface using Streamlit
    """
    console.print(
        Panel.fit(
            Text("FivcPlayground Web Interface", style="bold green"),
            subtitle="Starting Streamlit Application",
        )
    )

    try:
        console.print(f"[blue]Starting web interface at http://{host}:{port}[/blue]")
        console.print("[yellow]Press Ctrl+C to stop the server[/yellow]")

        # Get the path to the labs module
        app_path = os.path.join(os.path.dirname(__file__), "labs", "__init__.py")

        # Build streamlit command
        cmd = [
            sys.executable,
            "-m",
            "streamlit",
            "run",
            app_path,
            "--server.port",
            str(port),
            "--server.address",
            host,
            "--server.headless",
            "true",
            "--browser.gatherUsageStats",
            "false",
        ]

        if not debug:
            cmd.extend(["--logger.level", "error"])

        # Run streamlit
        subprocess.run(cmd, check=True)

    except KeyboardInterrupt:
        console.print("\n[yellow]Web interface stopped by user[/yellow]")
    except subprocess.CalledProcessError as e:
        console.print(f"[red]❌ Error starting web interface: {e}[/red]")
        console.print(
            "[yellow]Make sure Streamlit is installed: pip install streamlit[/yellow]"
        )
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]❌ Unexpected error: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def info():
    """
    Show information about FivcPlayground
    """
    info_text = """
    [bold blue]FivcPlayground[/bold blue]

    An intelligent agent ecosystem for autonomous tool generation,
    decision optimization, and dynamic crew orchestration.

    [bold]Features:[/bold]
    • Intelligent task assessment with consultant agents
    • Dynamic crew assembly based on task complexity
    • Autonomous tool generation and optimization
    • Event-driven agent orchestration

    [bold]Usage Examples:[/bold]
    fivcplayground run Generic                                         # Interactive mode
    fivcplayground run Generic --query "What is machine learning?"     # Programmatic mode
    fivcplayground web                                                 # Launch web interface
    fivcplayground clean                                               # Clean temporary files
    fivcplayground setup                                               # Initialize configuration
    fivcplayground info
    """

    console.print(Panel(info_text, title="FivcPlayground", border_style="blue"))


@app.command()
def setup(
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing configuration files without prompting",
    ),
):
    """
    Initialize FivcPlayground configuration directory structure.

    Creates .fivcplayground/configs/ directory in the current working directory
    and copies example configuration files from the project.
    """
    console.print(
        Panel.fit(
            Text("FivcPlayground Setup", style="bold cyan"),
            subtitle="Initializing Configuration",
        )
    )

    try:
        # Get current working directory
        cwd = Path.cwd()
        config_dir = cwd / ".fivcplayground" / "configs"

        # Get the project's configs directory
        project_root = Path(__file__).parent.parent.parent
        project_configs_dir = project_root / "configs"

        # Verify project configs directory exists
        if not project_configs_dir.exists():
            console.print(
                f"[red]❌ Error: Project configs directory not found at {project_configs_dir}[/red]"
            )
            raise typer.Exit(1)

        # Configuration files to copy
        config_files = [
            ("agents.yaml.example", "agents.yaml"),
            ("models.yaml.example", "models.yaml"),
            ("embeddings.yaml.example", "embeddings.yaml"),
            ("tools.yaml.example", "tools.yaml"),
        ]

        # Create config directory if it doesn't exist
        config_dir.mkdir(parents=True, exist_ok=True)
        console.print(f"[blue]📁 Created directory: {config_dir}[/blue]")

        # Track copied files
        copied_files = []
        skipped_files = []

        # Copy each configuration file
        for source_name, target_name in config_files:
            source_file = project_configs_dir / source_name
            target_file = config_dir / target_name

            # Check if source file exists
            if not source_file.exists():
                console.print(
                    f"[yellow]⚠️  Warning: Source file not found: {source_file}[/yellow]"
                )
                skipped_files.append(source_name)
                continue

            # Check if target file already exists
            if target_file.exists() and not force:
                overwrite = typer.confirm(
                    f"File {target_name} already exists. Overwrite?",
                    default=False,
                )
                if not overwrite:
                    console.print(f"[yellow]⏭️  Skipped: {target_name}[/yellow]")
                    skipped_files.append(target_name)
                    continue

            # Copy file with metadata preservation
            try:
                shutil.copy2(source_file, target_file)
                copied_files.append(target_name)
                console.print(f"[green]✅ Copied: {target_name}[/green]")
            except Exception as e:
                console.print(f"[red]❌ Error copying {target_name}: {e}[/red]")
                raise typer.Exit(1)

        # Display summary
        console.print("\n" + "=" * 60)
        console.print("[bold cyan]Setup Summary[/bold cyan]")
        console.print("=" * 60)
        console.print(f"[blue]Configuration directory:[/blue] {config_dir}")
        console.print(f"[green]Files copied: {len(copied_files)}[/green]")
        if copied_files:
            for file in copied_files:
                console.print(f"  • {file}")
        if skipped_files:
            console.print(f"[yellow]Files skipped: {len(skipped_files)}[/yellow]")
            for file in skipped_files:
                console.print(f"  • {file}")

        # Display next steps
        console.print("\n[bold cyan]Next Steps:[/bold cyan]")
        console.print(f"1. Edit configuration files in: [blue]{config_dir}[/blue]")
        console.print("2. Configure your LLM provider (models.yaml)")
        console.print("3. Configure agents (agents.yaml)")
        console.print("4. Configure embeddings (embeddings.yaml)")
        console.print("5. Configure tools (tools.yaml)")
        console.print("\n[green]✅ Setup completed successfully![/green]")

        embedding_backend = ChromaEmbeddingBackend()
        embedding_config_repository = FileEmbeddingConfigRepository()

        tool_backend = StrandsToolBackend()
        tool_config_repository = FileToolConfigRepository()

        tools = asyncio.run(create_builtin_tools_async(tool_backend=tool_backend))
        tool_retriever = asyncio.run(
            create_tool_retriever_async(
                tools=tools,
                tool_backend=tool_backend,
                tool_config_repository=tool_config_repository,
                embedding_backend=embedding_backend,
                embedding_config_repository=embedding_config_repository,
                embedding_config_id="default",
                raise_exception=False,
            )
        )
        if tool_retriever:
            asyncio.run(tool_retriever.index_tools_async())

    except typer.Exit:
        raise
    except Exception as e:
        import traceback

        console.print(f"[red]❌ Setup failed: {e}[/red]")
        console.print(traceback.format_exc())
        raise typer.Exit(1)


def main():
    """
    Main entry point for the CLI
    """
    app()


if __name__ == "__main__":
    main()
