__all__ = [
    "TaskRunContent",
    "TaskRunStatus",
    "TaskRunEvent",
    "TaskRunPhase",
    "TaskRun",
    "TaskRunnable",
    "TaskSimpleRunnable",
]

from abc import abstractmethod, ABC
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Literal
from uuid import uuid4

from pydantic import BaseModel, Field, computed_field

from fivcplayground.agents import (
    AgentRunStatus as TaskRunStatus,
    AgentRunContent as TaskRunContent,
    AgentRunnable as TaskRunnable,
    AgentConfig as TaskPlanAgent,
    AgentBackend,
    AgentConfigRepository,
)
from fivcplayground.models import (
    ModelBackend,
    ModelConfigRepository,
)


class TaskPlanOption(BaseModel):
    """Task plan option."""

    name: Literal["sequential", "swarm"] = Field(..., description="Name of the option")
    content: dict = Field(default={}, description="Content of the option")


class TaskPlan(BaseModel):
    """Task plan."""

    id: str = Field(..., description="Unique identifier for the task")

    @computed_field
    @property
    def name(self) -> str:
        return self.id  # id and name are the same for task

    description: str = Field(..., description="Description of the task")

    agents: list[TaskPlanAgent] = Field(
        description="List of agents needed for the task"
    )
    options: TaskPlanOption | None = Field(
        default=None, description="Options for the task"
    )


class TaskRunEvent(str, Enum):
    """Task runtime event enumeration."""

    START = "start"
    FINISH = "finish"
    UPDATE = "update"


class TaskRunPhase(BaseModel):
    """Single task execution step record."""

    model_config = {"arbitrary_types_allowed": True}

    id: str = Field(default=None, description="Unique identifier for the phase")
    agent_id: str = Field(description="ID of the agent executing this phase")

    status: TaskRunStatus = Field(
        default=TaskRunStatus.PENDING, description="Current execution status"
    )
    started_at: Optional[datetime] = Field(
        default=None, description="Step start timestamp"
    )
    completed_at: Optional[datetime] = Field(
        default=None, description="Step completion timestamp"
    )
    messages: List[TaskRunContent] = Field(
        default_factory=list, description="Messages during execution"
    )
    error: Optional[str] = Field(default=None, description="Error message if failed")

    @computed_field
    @property
    def duration(self) -> Optional[float]:
        """Get execution duration in seconds"""
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @computed_field
    @property
    def is_running(self) -> bool:
        """Check if execution is currently runtime"""
        return self.status == TaskRunStatus.EXECUTING

    @computed_field
    @property
    def is_completed(self) -> bool:
        """Check if execution is completed (success or failure)"""
        return self.status in (TaskRunStatus.COMPLETED, TaskRunStatus.FAILED)


class TaskRun(BaseModel):
    """Task runtime execution metadata."""

    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique task ID")

    @computed_field
    @property
    def task_id(self) -> str:  # same as id
        return self.id

    query: Optional[str] = Field(default=None, description="User query for the task")
    plan: Optional[TaskPlan] = Field(
        default=None, description="Task plan generated by the planner agent"
    )
    status: TaskRunStatus = Field(
        default=TaskRunStatus.PENDING, description="Current execution status"
    )
    started_at: Optional[datetime] = Field(
        default=None, description="Task start timestamp"
    )
    completed_at: Optional[datetime] = Field(
        default=None, description="Task completion timestamp"
    )
    phases: Dict[str, TaskRunPhase] = Field(
        default_factory=dict, description="Task execution phases"
    )

    @computed_field
    @property
    def duration(self) -> Optional[float]:
        """Get task duration in seconds"""
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None

    @computed_field
    @property
    def is_completed(self) -> bool:
        """Check if task is completed (success or failure)"""
        return self.status in (TaskRunStatus.COMPLETED, TaskRunStatus.FAILED)

    def sync_status(self):
        """Synchronize task status based on phase statuses."""
        if any(
            phase.status == TaskRunStatus.EXECUTING for phase in self.phases.values()
        ):
            self.status = TaskRunStatus.EXECUTING
        elif any(
            phase.status == TaskRunStatus.FAILED for phase in self.phases.values()
        ):
            self.status = TaskRunStatus.FAILED
        elif all(
            phase.status == TaskRunStatus.COMPLETED for phase in self.phases.values()
        ):
            self.status = TaskRunStatus.COMPLETED
        else:
            self.status = TaskRunStatus.PENDING

    def sync_started_at(self):
        """Synchronize task start timestamp based on phase timestamps."""
        if self.phases:
            self.started_at = min(
                phase.started_at for phase in self.phases.values() if phase.started_at
            )

    def sync_completed_at(self):
        """Synchronize task completion timestamp based on phase timestamps."""
        if self.phases:
            self.completed_at = max(
                phase.completed_at
                for phase in self.phases.values()
                if phase.completed_at
            )

    def sync(self) -> "TaskRun":
        """Synchronize all task metadata based on step data."""
        self.sync_status()
        self.sync_started_at()
        self.sync_completed_at()
        return self

    def cleanup(self):
        """Clean up task data and reset to initial state."""
        self.status = TaskRunStatus.PENDING
        self.started_at = None
        self.completed_at = None
        self.phases.clear()


class TaskSimpleRunnable(TaskRunnable):
    """
    Simple task runnable for testing and development.

    This class provides a basic implementation of the Runnable interface
    for testing and development purposes. It does not perform any actual
    task execution, but simply returns a predefined result.
    """

    def __init__(self, runnable: TaskRunnable, query: str = "", **kwargs):
        self._query = query
        self._kwargs = kwargs
        self._runnable = runnable

    @property
    def id(self) -> str:
        return self._runnable.id

    @property
    def name(self) -> str:
        return self._runnable.name

    @property
    def description(self) -> str:
        return self._runnable.description

    def run(self, query: str = "", **kwargs) -> BaseModel:
        kwargs.update(query=self._query.format(query=query))
        for k, v in self._kwargs.items():
            kwargs.setdefault(k, v)
        return self._runnable.run(**kwargs)

    async def run_async(self, query: str = "", **kwargs) -> BaseModel:
        kwargs.update(query=self._query.format(query=query))
        for k, v in self._kwargs.items():
            kwargs.setdefault(k, v)
        return await self._runnable.run_async(**kwargs)


class TaskBackend(ABC):
    """Interface for task backends."""

    @abstractmethod
    async def create_task_async(
        self,
        model_backend: ModelBackend,
        model_config_repository: ModelConfigRepository,
        agent_backend: AgentBackend,
        agent_config_repository: AgentConfigRepository,
        task_plan: TaskPlan,
        task_response_model: BaseModel | None = None,
        **kwargs,  # ignore additional kwargs
    ) -> TaskRunnable:
        """Create a task instance from a TaskPlan."""
